# Schema for the configuration files of the crm_core_default_matching_engine module.

crm_core_match.configuration.default:
  type: mapping
  mapping:
    threshold:
      type: integer
      label: 'Match score threshold'
    return_order:
      type: string
      label: 'Return order'
    strict:
      type: boolean
      label: 'Strict matching'
    rules:
      label: 'Rules'
      type: sequence
      sequence:
        # This sequence is keyed by field names.
        type: sequence
        label: Field
        sequence:
        # This sequence is keyed by field property names.
          type: mapping
          label: Field property
          mapping:
            weight:
              type: integer
              label: 'Weight'
            status:
              type: boolean
              label: Enabled
            operator:
              type: string
              label: Operator
            options:
              type: string
              label: Options
            score:
              type: integer
              label: Score
