# Schema for the configuration files of the crm_core_activity module.

crm_core_default_matching_engine.rule.*:
  type: config_entity
  label: 'Matching rule'
  mapping:
    label:
      type: label
      label: 'Entity label'
    type:
      type: string
      label: 'Identifier'
    threshold:
      type: integer
      label: 'Match score threshold'
    return_order:
      type: string
      label: 'Return order'
    strict:
      type: boolean
      label: 'Strict matching'
    rules:
      label: 'Rules'
      type: sequence
      sequence:
        type: mapping
        label: Field
        mapping:
          weight:
            type: integer
            label: 'Weight'
          status:
            type: boolean
            label: Enabled
          operator:
            type: string
            label: Operator
          options:
            type: string
            label: Options
          score:
            type: integer
            label: Score
